eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
spring:
  cloud:
    config:
      override-system-properties: false  

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:9098/realms/ecommerce}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:9098/realms/ecommerce/protocol/openid-connect/certs}

management:
  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
    export:
      zipkin:
        enabled: ${ZIPKIN_ENABLED:true}
        endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
        connect-timeout: 2s
        read-timeout: 5s

application:
  kafka:
    product-reservation-requested-topic: product.reservation.requested
    product-reservation-succeeded-topic: product.reservation.succeeded
    product-reservation-failed-topic: product.reservation.failed
    payment-requested-topic: payment.requested
    payment-confirmed-topic: payment.confirmed
    payment-failed-topic: payment.failed
    order-confirmed-topic: order.confirmed
    order-cancelled-topic: order.cancelled
    notification-requested-topic: notification.requested
