spring:
  mongodb:
    username: ${MONGODB_USERNAME:mongodb}
    password: ${MONGODB_PASSWORD:mongodb}
    host: ${MONGODB_HOST:localhost}
    port: ${MONGODB_PORT:27017}
    database: ${MONGODB_DATABASE:customer}
    authentication-database: ${MONGODB_AUTHENTICATION_DATABASE:admin}
      
server:
  port: 8090
