spring:
  application:
    name: discovery-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      enabled: ${CONFIG_ENABLED:false}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 60
        multiplier: 1.2
        max-interval: 10000
